### ISSUE TITLE
Range 16 CAS scenario, mortars

### ISSUE THREAD

**Issue by steven-omaha** [132nd-vWing/ATRM#111]
The friendly mortars in the mentioned scenarios announced two fire missions ahead of time. I only saw the second one, and missed the first. Was surprised by explosions not too far away.  Can we please have a "radio beep sound" when the JTAC receives a simulated radio call?

Also, the second fire mission was apparently broken. It was announced, but the mortars never fired.

**Comment by steven-omaha** [comment]
I'm not sure why this was closed without comment.

In yesterday's training the second fire mission worked ok.

> Can we please have a "radio beep sound" when the JTAC receives a simulated radio call?

This one is still relevant. I missed the announcement of the first fire mission, yet again.

**Comment by 132nd-Entropy** [comment]
I had probably closed it because it has been weeks since it was posted and not been worked on, but tbh I cant remember, it could aslo have been a misclick. this is no scripting issue, in fact, as I wrote iirc in a related issue that basically said the same thing (maybe thats why I had closed it, not sure) those scenarios were done via ME triggers, not script. Could you not simply add the sound and upload a new version?

**Comment by steven-omaha** [comment]
I will give it a try in the next days. Thanks.

**Comment by IAFAssafB** [comment]
Apologies, 
Can't find time to get into working on this issue.
