### ISSUE TITLE
KC135 speeds ( 20k ones - AR201, AR202, AR203 and AR402) are rather low

### ISSUE THREAD

**Issue by hbjonsson** [132nd-vWing/ATRM#118]
Currently KC135 speeds for AR tracks at 20.000ft are set to 317kts in the ME. This results in a KCAS of 277 knots which is on the low end, making refueling slightly more challenging. 

Setting this speed to 417kts ( resulting in a 310KCAS) is a preferable speed for pointy nose jets. 

A10´s should not be affected as they use AR101 at FL120...

/ Jester

**Comment by 132ndNeck** [comment]
This have been set the way they are as a compromise.
Having higher speeds will increase the time pilots chase the tanker for rejoin. Since we can not control the tanker intercept, and need to have it in a racetrack we can not get any help from the tanker in any way.
So, to maximize the training value of a evening, we want to reduce the time needed for rejoining the tanker and chasing the tanker, hence the slightly lower speed.

And, yes, this may make AAR slightly more challenging, but that should not be a factor, as it is a basic skill that all pilots need to master in a good way to be a 338 pilot (since these tankers are only used by the 338). But, the argument that it is slightly more challenging is not a big problem, since no pilot have had this a major issue for completing their training.

As a compromize, I can adjust the tanker speed for the combat missions. I just need to know what mach number they should be at. As the current tankers mentioned in the ATRM is set at M0.6 regardless of altitude.
