### ISSUE TITLE
ATIS at OMAM INOP

### ISSUE THREAD

**Issue by steven-omaha** [132nd-vWing/ATRM#121]
Today's training is the second event where we had no ATIS. So apparently something broke ATIS in one of the recent edits.

**Comment by 132nd-Entropy** [comment]
Datis is in use not moose atis, @132ndNeck set that up, not sure how that works

**Comment by martinco** [comment]
@steven-omaha @132ndNeck The mission file is fine / no breakage

The issue was that Google API now requires billing to be active (as seen in `DCS.openbeta_server\Logs\DATIS.log` with a permission denied / message

For the time being i have updated the options.lua API Key to my own and will advise if it starts racking up any significant bills, i doubt it will

```
Feature                       | Free per month            | Price after free quota is reached
Standard (non-WaveNet) voices | 0 to 4 million characters | $4.00 USD / 1 million characters
```

I backed up the old `options.lua` to `options.martinco.2021-03-19.lua` or similar name :)

**Comment by steven-omaha** [comment]
Awesome, thanks a lot!

Just did a quick estimation, we should have about 1.5 million characters a month, so roughly 6 dollar.
