### ISSUE TITLE
24th Gazelle Laser Designation Support

### ISSUE THREAD

**Issue by victrox-dev** [132nd-vWing/ATRM#123]
Currently, the 24th is utilizing the Gazelle during extra training events IOT develop SOP's and TTP's in preparation for the end-goal airframe being the Kiowa. A user by the name of CakeSorbus developed a script to bring a little bit of the Kiowa's features to the Gazelle, namely laser designation. https://forums.eagle.ru/topic/262118-gazdesignate-laser-designator-script-for-sa342m-gazelle/?tab=comments

In the pursuit of a Kiowa-esque experience to temporarily support our mission goals, the 24th is requesting the addition of this script. It adds laser-designation functionality via the F10 menu, only functions with the Mike model Gazelle and only appears in the Gazelle's F10 menu. The script essentially attaches to and follows the stare-point of the Viviane sighting camera when it is powered on. PRF can be changed via F10 and laser-designation can be switched on/off via the same methods.

Attached is the modified script, specific to the ATRM's Gazelle pilot names. IOT implement the script, a simple trigger with "time (more)" than x amount of seconds will work fine; or MISSION START trigger.
[GazDesignatorScript.zip](https://github.com/132nd-vWing/ATRM/files/6225307/GazDesignatorScript.zip)

This will enable us to practice laser-handoff, buddy lasing, etc. w/FW assets so that we may perform these tasks to a greater standard upon the release of the Kiowa.

Thank you for your consideration,
-Sly

**Comment by 132ndNeck** [comment]
I think this will not be supported.
If we need to mod exsisting modules in order to simulate future modules, I think we start on a spiral downward in a way we do not want to end up. 

Laser handoff is a fairly simple thing to train, so it is not crucial for the development of the 24th. It is better to wait for the release of the actual module for this specific item, so we do not start modding aircrafts because we want them to be something else.
I know it is meant well, and for this specific item only, but I prefer not to do it.
