### ISSUE TITLE
Gazelles are parked in a unfortunate position according to Sly - move nearby KA-50s

### ISSUE THREAD

**Issue by hbjonsson** [132nd-vWing/ATRM#130]
The Gazelles are parked in the back away from the others - this would move them by the KA-50´s as was requested by Sly on the "hot weather" training event. Those positions worked out fine according to Sly.

![image](https://user-images.githubusercontent.com/25992707/120234645-f2fc0000-c247-11eb-98eb-2879c5966d82.png)

**Comment by hbjonsson** [comment]
According to Sly, the Gazelles don´t get ground power from where they were before.

**Comment by victrox-dev** [comment]
Correct. In their current position on APRON 1 Center they don't get ground power. As pictured above on APRON 1 East they work as intended. In addition, now that the 24th is active... we need to add 10xSA342M and 2xSA342L to bring the total count to 8xSA342M at OMAL and OMAM, with 4xSA342L at both airfields as well. The only way to manage this with the limited space available at OMAM is to reoganize the KA-50's and Mi-8's manually on the APRON instead of letting DCS assign them to parking spots.

My proposal is to do so by arranging them sequentially in a line facing the taxi-way; this will free up a lot of space in that area.

**Comment by steven-omaha** [comment]
Looking good.
