### ISSUE TITLE
Range 3 SAMs

### ISSUE THREAD

**Issue by 132nd-FurFace** [132nd-vWing/ATRM#132]
**Describe the bug**

Should SA-15 missiles be able to destroy aircraft in Range 3?  Whilst undertaking a SCUD hunt in range 3 I was engaged by a SA-15.  A missile hit and destroyed my aircraft.  

**Expected behavior**

My understanding is that a script should prevent aircraft destruction, but produce a message saying destroyed.

**Comment by 132nd-Professor** [comment]
That should not have happened. Ashilta confirmed that saw a message from the missile script, therefore it was active. I can only conclude that it failed in this case. I will have a look at tacview and the script parameters.

**Comment by 132nd-Professor** [comment]
I had a look at my tacview file from yesterday and the FOX script.

* You received a total of 4 missile launches from two different SA-15s. You defeated the first two. FOX apparently registered a hit on the third, but did not get the fourth, which in turn killed you.
* The FOX missile script is currently set to a distance of 20 meters. If a missile is within a 20m radius bubble of the target aircraft, it will be destroyed.
* We had issues with FOX in the past, but it has been working reliably in the past months. The last change was authored by Entropy (db18ff2d) on December 20th, and I have no recollections of issues since then.
* The only thing I can do is increase the distance to something larger, but even that is no guarantee this will work in all cases.
* From what I remember 20 meters is a good value for A2A practice.

Therefore I am hesitant to change anything at this time. Please let us know if FOX misses any more missiles. If you want to be absolutely safe, you can also take any of the invulnerable A-10C in ATRM.
