### ISSUE TITLE
A-A

### ISSUE THREAD

**Issue by kimkiller65** [132nd-vWing/ATRM#2]
Is there a way to have a scripted A-A training area with different opponents and numbers?

**Comment by 132ndNeck** [comment]
Maybe.
I am not a big fan of AI flights on the training map. But I will look into it and check the airspace.

**Comment by abeardedbear** [comment]
What about popping drones out from the F10?

**Comment by 132ndNeck** [comment]
Are we not able to rally pilots to train against Human pilots?

**Comment by abeardedbear** [comment]
Yes, most of the time is true and always the better choice. But sometimes we lack the numbers, for example to do TAC04, if nobody's available having a drone is quite good to focus on the talk on and procedures for the trainee. Beyond that I do agree it is not really necessary, but this could be a quality of life features where no other pilot is available.

**Comment by kimkiller65** [comment]
I think you can get some human pilots for regular training but it is hard to find arrange two 2 ships and if you do, they want to get some practice out of it too.
In my opinion the only reasons for not having A-A AI in a confined area would be if the script affects the training mission negatively in any way, such as making it too big, crashing, or cannot be confined in the certain area.

**Comment by thebgpikester** [comment]
As per question on Discord. AI misbehaving isn't an issue, we've flown OPUF 14-15 times with replays and the only tanker/awacs shoot down was by the non MOOSE scripted AI. The script doesn't run amok outside it's scope and config. It can be enhanced, AI can be deleted automously outside it's area, but its not required on the size of map PG is.

The _real_ question is that if A2A with AI and Helicopter/FW strike/CAS and everything else training will never coexist in the same TRM by choice, it forces one of two things:

1) People form groups up and play without other people in all sorts of times without 132nd limitations and management.

or

2) People have to create another official training night each week.

(1) is bad because not having A-A as official training is terrible. It's focused, difficult to train, requires coordination, proper radio setup, controllers which are hard to get, and if its not done officially, it will end up not training but some PvP session.

(2) Is unlikely because; with 1 training and one mission a week, a third night flying with full MDC, planning and whatnot becomes too much for the average person", so it has to end up "casual" - see point (1). 

This is why I'd rather they coexisted as one mission file and session.

**Comment by 132nd-Entropy** [comment]
closing this as the use if AI planes came up multiple times and never was approved
