### ISSUE TITLE
F16 UHF Presets A/C on Apron 6

### ISSUE THREAD

**Issue by daviddcs** [132nd-vWing/ATRM#39]
Preset #2 was not 237 as per Preset Sheet, believe it was 229 or similar.

This was the same for two A/C parked Apron 6, another Viper on different apron had correct freq.

**Comment by 132ndNeck** [comment]
![bilde](https://user-images.githubusercontent.com/26002570/68069754-fa55e180-fd64-11e9-9be3-e2a366708c69.png)
This is  a screenshot from the ME on the freqs that are programmed into the F16 at Apron 6.
All 4 AC have 237 as preset 2.

So, I am not sure what causes the issue, so this require further testing.

**Comment by 132ndNeck** [comment]
Tested now, and 237 was at preset 1, even though it is set in the mission editor as shown above
(tested in MP on the 132nd server)

**Comment by daviddcs** [comment]
Silly me I forgot it was bugged :) does the same on the TRM, victor works but uniform presets are bust.

**Comment by daviddcs** [comment]
Not ATRM related.

**Comment by hbjonsson** [comment]
Please re-open - this bug has been fixed by ED.
https://forums.eagle.ru/topic/226274-a10c-radio-presets-overwrite-the-viper-presets/

ATRM needs to be re-saved then prepare-mission re-run.

In doing so an Avionics\F-16C_50\166\UHF_RADIO\SETTINGS.lua and Avionics\F-16C_50\166\VHF_RADIO\SETTINGS.lua are generated. 

These files likely need to be updated manually as changes in the editor do not seem to propagate to these files.

**Comment by hbjonsson** [comment]
So **166** is the unit ID of the F16. - the change must be done for each F16 unitID.
