### ISSUE TITLE
Add frigates and Tarawa

### ISSUE THREAD

**Issue by Looney1976** [132nd-vWing/ATRM#58]
If possible, please add the Tarawa and at least 2 frigates close to the coast near Al Dhafra to allow RW pilots to train maritime operations.

**Comment by 132nd-Entropy** [comment]
@Looney1976 if an open issue was not addressed so long, it's best to bump it. I don't see any issue with it (Im just doing the scripts, not the design). Since @132ndNeck didnt disagree I think it's safe for you to grab the latest miz, do the proposed changes, and send to me via discord so I can make a new release

**Comment by 132nd-Entropy** [comment]
Thanks for adding them @Looney1976

**Comment by 132ndNeck** [comment]
The ships fire at RED AIR aicraft (messing up me an Kimkillers training yesterday).

We have not had 259th MI-8ts flying on the ATRM as far as I can recall?
So do we really need to add ships with radars that will add strain on the server that are not to be used?

- If ships are to be used I rather have them F10 spawnable, because I expect them to be used extremely rarely.

- Second, how do we plan using ship operations in missions? It is no point adding ships if we dont have a use for it in a mission?  (Personal oppionion, and open for discussion on this)

- Third, why do we need so many ships?

- Fourth, if ships are to be added they can not shoot down redair, as both the tanker for MOA1/Range 1 gets killed, and any red air operating in the area


I will delete the ships in the current mission

**Comment by steven-omaha** [comment]
How about setting the ships to green state instead

**Comment by Looney1976** [comment]
I've flown the Mi8 on the PG ATRM a couple of times. It's a double-edged sword. If the ATRM doesn't provide for stuff to do for the Mi-8, you won't see pilots signing up for it and we basically end-up spiralling down from there.

The ships can be set to green state or remove their weapons as they're there to provide naval training for the helicopters.

The general idea is that once the wing goes naval/amphibious, the different squadrons that can operate from a ship (494, 259, 696, 108, 176) should be able to to conduct training.

**Comment by 132nd-Entropy** [comment]
I added the ships back. Now they are properly set to Green State and won't attack anything. 
Also, they won't be there by default, they need to be spawned via F10 menu
 (under misc)

**Comment by 132nd-Entropy** [comment]
opening this up for discussion. If they still shall be removed, let me know
