### ISSUE TITLE
MOA 2 Space

### ISSUE THREAD

**Issue by abeardedbear** [132nd-vWing/ATRM#75]
MOA2 could be extended on the NW side for another 12nm into the sea, and the SE side 5nm inland. This is to accommodate Long Range A2A training for tomcats and to easily be accessible from al dhafra

**Comment by jkhoel** [comment]
Isn't it better to extend it 17nm into the sea and leave as-is inland? There is a corridor passing north to south on the east side of MOA2. There is also tanker tracks to the south of it. So but to the North and West there is empty space

**Comment by martinco** [comment]
I think that's what he means

Extend north 5-10 nm (right side following TC)
Extend horizontally (into the sea) 12nm 

There is also the Stennis to the left of musa but this stops short of the island so should be clear of there

**Comment by 132ndNeck** [comment]
I do not have DCS on my laptop, so unable to check before this evening.
But with the Carrier having a carrier control zone of 50nm, I think the reason why I did not make MOA 2 bigger, was to make sure to have an area for the carrier to operate, and a bigger MOA 2 would come in conflict MOA 2.

- There should not be a problem expanding MOA 2 to the WEST/SOUTH WEST, as long as it is fine for the carrier based squadrons (494th and 108th), and that there will be no conflict with carrier operations (to include case 3 ).
- However a expansion towards the EAST is not possible due to the transit corridor.
- Expansion North also difficult due to the airfield that are north (Al Maktoum International)

**Comment by 132Ashilta** [comment]
To help the discussion: I've plotted the location of Stennis in Combat Flite and marked a 50nm ring: https://imgur.com/a/5mQtIyx

**Comment by martinco** [comment]
This is the view in ME:

![before](https://user-images.githubusercontent.com/250888/75357418-434c1b80-58a9-11ea-98b0-71f5b9c730f2.png)

And After

![after](https://user-images.githubusercontent.com/250888/75357420-43e4b200-58a9-11ea-8d6b-5366b000a874.png)

That's the AWACS track to the west edge

**Comment by abeardedbear** [comment]
The reason behind this request is to have a 60nm axis to use when we want to train with and against the AIM54

The request on MOA2 rather than 1, is because 2 is closer to OMAM, and this gets us 20 minutes less of travelling to get there and start doing stuff. Also, there are tankers nearby. 
If A2A training consists of briefing, practice and repetition, and in the end a detailed debrief that can last another 20m, that travelling time is quite cumbersome. 

MOA1 is super handy for ships that can take off and land from the carrier, for such training. 
Yes, tonight we may be hornets and tomcats, but this idea should be extended also for the vipers.

**Comment by 132nd-Entropy** [comment]
any update on this ?
