### ISSUE TITLE
Tanker S3 near Stennis disapeared 

### ISSUE THREAD

**Issue by 132ndhitch** [132nd-vWing/ATRM#83]
After a minute the tanker jerked and I was disconnected. On the second attempt, the tanker suddenly disappeared.

**Comment by 132nd-Entropy** [comment]
there is a problem with the latest DCS that affects all scripts using the AIRBASE class. Moose developers are on it, but it turns out to be a tricky thing. I can imagine this is related to that bug, as nothing was changed in our script and the recovery tanker used to work just fine.

**Comment by 132nd-Entropy** [comment]
actually, this might be intended behavior. When the tanker is empty, it would fly back to the Stennis, land, park and a new one will launch. However, do not have AI flights enter the pattern and disrupt operations, we set it so that the new tanker will spawn in mid air. thats probably what happend to you.

**Comment by 132ndhitch** [comment]
Tanker has ~ 7000 LBS fuel, I used ~1000LBS.
